# Text generation using a RNN with eager execution

(Adapted from the tensorflow example https://www.tensorflow.org/tutorials/sequences/text_generation)

This tutorial demonstrates how to generate text using a character-based RNN. We will work with a dataset of Shakespeare's writing from Andrej Karpathy's [The Unreasonable Effectiveness of Recurrent Neural Networks](http://karpathy.github.io/2015/05/21/rnn-effectiveness/). Given a sequence of characters from this data ("Shakespear"), train a model to predict the next character in the sequence ("e"). Longer sequences of text can be generated by calling the model repeatedly.

This tutorial includes runnable code implemented using [tf.keras](https://www.tensorflow.org/programmers_guide/keras) and [eager execution](https://www.tensorflow.org/programmers_guide/eager). The following is sample output when the model in this tutorial trained for 30 epochs, and started with the string "Q":

<pre>
QUEENE:
I had thought thou hadst a Roman; for the oracle,
Thus by All bids the man against the word,
Which are so weak of care, by old care done;
Your children were in your holy love,
And the precipitation through the bleeding throne.

BISHOP OF ELY:
Marry, and will, my lord, to weep in such a one were prettiest;
Yet now I was adopted heir
Of the world's lamentable day,
To watch the next way with his father with his face?

ESCALUS:
The cause why then we are all resolved more sons.

VOLUMNIA:
O, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, it is no sin it should be dead,
And love and pale as any will to that word.

QUEEN ELIZABETH:
But how long have I heard the soul for this world,
And show his hands of life be proved to stand.

PETRUCHIO:
I say he look'd on, if I must be content
To stay him from the fatal of our country's bliss.
His lordship pluck'd from this sentence then for prey,
And then let us twain, being the moon,
were she such a case as fills m
</pre>

While some of the sentences are grammatical, most do not make sense. The model has not learned the meaning of words, but consider:

* The model is character-based. When training started, the model did not know how to spell an English word, or that words were even a unit of text.

* The structure of the output resembles a play—blocks of text generally begin with a speaker name, in all capital letters similar to the dataset.

* As demonstrated below, the model is trained on small batches of text (100 characters each), and is still able to generate a longer sequence of text with coherent structure.

## Goals

- Understand the evolution of samples during training, and the relationship between the number of training ephocs and the quality of the generated output. 
- Produce (or download) your own textual corpus to experiment with parameters, training, and results. In [his article](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) cited above, Karpathy plays with sources including Shakespeare, Wikipedia articles, Algebraic Geometry (Latex), and Linux source code, and baby names.
E

## Setup

### Import TensorFlow and other libraries

In [45]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf
tf.enable_eager_execution()

import numpy as np
import os
import time

### Download the Shakespeare dataset

Change the following line to run this code on your own data.

In [46]:
path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

# path_to_file = "try_with_your_own_file.txt"




### Read the data

First, look in the text.

In [47]:
# Read, then decode for py2 compat.
text = open(path_to_file, 'rb').read().decode(encoding='utf-8')
# length of text is the number of characters in it
print ('Length of text: {} characters'.format(len(text)))

Length of text: 747567 characters


In [48]:
# Take a look at the first 250 characters in text
print(text[:250])



Reading Reference




Narratology: Introduction to the theory of Narrative, 3rd ed. Mieke Bal. 2009.

A narrative test is a text in which an agent or subject conveys to an addressee ('tells' the reader) a story in a particular medium, such as langu


In [49]:
# The unique characters in the file
vocab = sorted(set(text))
print ('{} unique characters'.format(len(vocab)))

110 unique characters


## Process the text

### Vectorize the text

Before training, we need to map strings to a numerical representation. Create two lookup tables: one mapping characters to numbers, and another for numbers to characters.

In [50]:
# Creating a mapping from unique characters to indices
char2idx = {u:i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)

text_as_int = np.array([char2idx[c] for c in text])

Now we have an integer representation for each character. Notice that we mapped the character as indexes from 0 to `len(unique)`.

In [51]:
print('{')
for char,_ in zip(char2idx, range(20)):
    print('  {:4s}: {:3d},'.format(repr(char), char2idx[char]))
print('  ...\n}')

{
  '\t':   0,
  '\n':   1,
  '\x0c':   2,
  '\r':   3,
  ' ' :   4,
  '!' :   5,
  '"' :   6,
  '#' :   7,
  '%' :   8,
  '&' :   9,
  "'" :  10,
  '(' :  11,
  ')' :  12,
  '*' :  13,
  '+' :  14,
  ',' :  15,
  '-' :  16,
  '.' :  17,
  '/' :  18,
  '0' :  19,
  ...
}


In [52]:
# Show how the first 13 characters from the text are mapped to integers
print ('{} ---- characters mapped to int ---- > {}'.format(repr(text[:13]), text_as_int[:13]))

'\n\nReading Ref' ---- characters mapped to int ---- > [ 1  1 52 69 65 68 73 78 71  4 52 69 70]


### The prediction task

Given a character, or a sequence of characters, what is the most probable next character? This is the task we're training the model to perform. The input to the model will be a sequence of characters, and we train the model to predict the output—the following character at each time step.

Since RNNs maintain an internal state that depends on the previously seen elements, given all the characters computed until this moment, what is the next character?


### Create training examples and targets

Next divide the text into example sequences. Each input sequence will contain `seq_length` characters from the text. 

For each input sequence, the corresponding targets contain the same length of text, except shifted one character to the right. 

So break the text into chunks of `seq_length+1`. For example, say `seq_length` is 4 and our text is "Hello". The input sequence would be "Hell", and the target sequence "ello".

To do this first use the `tf.data.Dataset.from_tensor_slices` function to convert the text vector into a stream of character indices.

In [53]:
# The maximum length sentence we want for a single input in characters
seq_length = 100
examples_per_epoch = len(text)//seq_length

# Create training examples / targets
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

for i in char_dataset.take(5):
  print(idx2char[i.numpy()])





R
e
a


The `batch` method lets us easily convert these individual characters to sequences of the desired size. 

In [54]:
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

for item in sequences.take(5):
  print(repr(''.join(idx2char[item.numpy()])))

'\n\nReading Reference\n\n\n\n\nNarratology: Introduction to the theory of Narrative, 3rd ed. Mieke Bal. 2009'
".\n\nA narrative test is a text in which an agent or subject conveys to an addressee ('tells' the reade"
'r) a story in a particular medium, such as language, imager, sound, buildings, r a combination thereo'
"f. A story is the fontent of that text, and produces a particular manifestation, inflection, and 'col"
"oring' of a fabula; the fabula is presented in a certain manner. A fabula is a series of logically an"


For each sequence, duplicate and shift it to form the input and target text by using the `map` method to apply a simple function to each batch:

In [55]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

Print the first examples input and target values:

In [56]:
for input_example, target_example in  dataset.take(1):
  print ('Input data: ', repr(''.join(idx2char[input_example.numpy()])))
  print ('Target data:', repr(''.join(idx2char[target_example.numpy()])))

Input data:  '\n\nReading Reference\n\n\n\n\nNarratology: Introduction to the theory of Narrative, 3rd ed. Mieke Bal. 200'
Target data: '\nReading Reference\n\n\n\n\nNarratology: Introduction to the theory of Narrative, 3rd ed. Mieke Bal. 2009'


Each index of these vectors are processed as one time step. For the input at time step 0, the model receives the index for "F" and trys to predict the index for "i" as the next character. At the next timestep, it does the same thing but the `RNN` considers the previous step context in addition to the current input character.

In [57]:
for i, (input_idx, target_idx) in enumerate(zip(input_example[:5], target_example[:5])):
    print("Step {:4d}".format(i))
    print("  input: {} ({:s})".format(input_idx, repr(idx2char[input_idx])))
    print("  expected output: {} ({:s})".format(target_idx, repr(idx2char[target_idx])))

Step    0
  input: 1 ('\n')
  expected output: 1 ('\n')
Step    1
  input: 1 ('\n')
  expected output: 52 ('R')
Step    2
  input: 52 ('R')
  expected output: 69 ('e')
Step    3
  input: 69 ('e')
  expected output: 65 ('a')
Step    4
  input: 65 ('a')
  expected output: 68 ('d')


### Create training batches

We used `tf.data` to split the text into manageable sequences. But before feeding this data into the model, we need to shuffle the data and pack it into batches.

In [58]:
# Batch size 
BATCH_SIZE = 64
steps_per_epoch = examples_per_epoch//BATCH_SIZE

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences, 
# so it doesn't attempt to shuffle the entire sequence in memory. Instead, 
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

dataset

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>

## Build The Model

Use `tf.keras.Sequential` to define the model. For this simple example three layers are used to define our model:

* `tf.keras.layers.Embedding`: The input layer. A trainable lookup table that will map the numbers of each character to a vector with `embedding_dim` dimensions;
* `tf.keras.layers.GRU`: A type of RNN with size `units=rnn_units` (You can also use a LSTM layer here.)
* `tf.keras.layers.Dense`: The output layer, with `vocab_size` outputs.

In [59]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension 
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

Next define a function to build the model.

Use `CuDNNGRU` if running on GPU.  

In [60]:
if tf.test.is_gpu_available():
  rnn = tf.keras.layers.CuDNNGRU
else:
  import functools
  rnn = functools.partial(
    tf.keras.layers.GRU, recurrent_activation='sigmoid')

In [61]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, 
                              batch_input_shape=[batch_size, None]),
    rnn(rnn_units,
        return_sequences=True, 
        recurrent_initializer='glorot_uniform',
        stateful=True),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model

In [62]:
model = build_model(
  vocab_size = len(vocab), 
  embedding_dim=embedding_dim, 
  rnn_units=rnn_units, 
  batch_size=BATCH_SIZE)

For each character the model looks up the embedding, runs the GRU one timestep with the embedding as input, and applies the dense layer to generate logits predicting the log-liklihood of the next character:

![A drawing of the data passing through the model](https://tensorflow.org/tutorials/sequences/images/text_generation_training.png)

## Try the model

Now run the model to see that it behaves as expected.

First check the shape of the output:

In [63]:
for input_example_batch, target_example_batch in dataset.take(1): 
  example_batch_predictions = model(input_example_batch)
  print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

(64, 100, 110) # (batch_size, sequence_length, vocab_size)


In the above example the sequence length of the input is `100` but the model can be run on inputs of any length: 

In [64]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (64, None, 256)           28160     
_________________________________________________________________
cu_dnngru_2 (CuDNNGRU)       (64, None, 1024)          3938304   
_________________________________________________________________
dense_2 (Dense)              (64, None, 110)           112750    
Total params: 4,079,214
Trainable params: 4,079,214
Non-trainable params: 0
_________________________________________________________________


To get actual predictions from the model we need to sample from the output distribution, to get actual character indices. This distribution is defined by the logits over the character vocabulary. 

Note: It is important to _sample_ from this distribution as taking the _argmax_ of the distribution can easily get the model stuck in a loop.

Try it for the first example in the batch:

In [65]:
sampled_indices = tf.random.multinomial(example_batch_predictions[0], num_samples=1) 
#sample_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

This gives us, at each timestep, a prediction of the next character index:

In [66]:
sampled_indices

array([ 41,  77,  62,  51,  23,   3,  20,   8,  52,   8,  74,   8,  14,
       107,  12,   9,   9,  64,  21,   7, 108,  33,  94,  25,  94,  50,
        89,  21,  86, 105,  84,  80,  82,  81,  41,  73,  86,  68,  58,
        17,  85,  64,  95,  54,  61,  43,  75,  28,  22,  80,   1,  12,
        75,  79,  68,  46,  57, 104,  89,  77,  96,  81,   1,  69,  28,
        55,  74, 103,  74,  18,  12,  38,  90,  94,   1,  78,  94,  92,
        38,  60,  58,  60,  62,  65,  98,  60,  45,  52,  61,   3,   9,
        22,  14,  44,  97,  28,  99,  55,   9,  73])

Decode these to see the text predicted by this untrained model:

In [67]:
print("Input: \n", repr("".join(idx2char[input_example_batch[0]])))
print()
print("Next Char Predictions: \n", repr("".join(idx2char[sampled_indices ])))

Input: 
 'pologist Claude Levi-Strauss characterizes two modes of thought, the mythical and the scientific. My'

Next Char Predictions: 
 'Gm]Q4\r1%R%j%+Ó)&&`2#Õ>\x8d6\x8dPy2vÑtprqGivdX.u`\x8eT[Ik93p\n)kodLWÐym\x93q\ne9UjÉj/)Dz\x8d\nn\x8d}DZXZ]a\x9dZKR[\r&3+J\x999\x9fU&i'


## Train the model

At this point the problem can be treated as a standard classification problem. Given the previous RNN state, and the input this time step, predict the class of the next character.

### Attach an optimizer, and a loss function

The standard `tf.keras.losses.sparse_softmax_crossentropy` loss function works in this case because it is applied across the last dimension of the predictions. 

Because our model returns logits, we need to set the `from_logits` flag. 


In [68]:
def loss(labels, logits):
#   return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)
  return tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits)

example_batch_loss  = loss(target_example_batch, example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)") 
print("scalar_loss:      ", example_batch_loss.numpy().mean())

Prediction shape:  (64, 100, 110)  # (batch_size, sequence_length, vocab_size)
scalar_loss:       4.701376


Configure the training procedure using the `tf.keras.Model.compile` method. We'll use `tf.train.AdamOptimizer` with default arguments and the loss function. 

In [69]:
model.compile(
    optimizer = tf.train.AdamOptimizer(),
    loss = loss)

### Configure checkpoints

Use a `tf.keras.callbacks.ModelCheckpoint` to ensure that checkpoints are saved during training:

In [70]:
# Directory where the checkpoints will be saved
checkpoint_dir = './text100'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

### Execute the training

To keep training time reasonable, use 3 epochs to train the model. In Colab, set the runtime to GPU for faster training.

In [71]:
EPOCHS=3

In [72]:
history = model.fit(dataset.repeat(), epochs=EPOCHS, steps_per_epoch=steps_per_epoch, callbacks=[checkpoint_callback])

Epoch 1/10
116/116 [==============================] - 7s 63ms/step - loss: 2.8899
Epoch 2/10
116/116 [==============================] - 7s 57ms/step - loss: 2.1782
Epoch 3/10
116/116 [==============================] - 6s 55ms/step - loss: 1.8924
Epoch 4/10
116/116 [==============================] - 7s 56ms/step - loss: 1.6824
Epoch 5/10
116/116 [==============================] - 6s 55ms/step - loss: 1.5467
Epoch 6/10
116/116 [==============================] - 6s 55ms/step - loss: 1.4590
Epoch 7/10
116/116 [==============================] - 6s 55ms/step - loss: 1.3957
Epoch 8/10
116/116 [==============================] - 7s 57ms/step - loss: 1.3442
Epoch 9/10
116/116 [==============================] - 7s 56ms/step - loss: 1.3018
Epoch 10/10
116/116 [==============================] - 6s 54ms/step - loss: 1.2615


## Generate text

### Restore the latest checkpoint

To keep this prediction step simple, use a batch size of 1.

Because of the way the RNN state is passed from timestep to timestep, the model only accepts a fixed batch size once built. 

To run the model with a different `batch_size`, we need to rebuild the model and restore the weights from the checkpoint.


In [73]:
tf.train.latest_checkpoint(checkpoint_dir)

'./text100/ckpt_10'

In [74]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1, None]))

In [75]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (1, None, 256)            28160     
_________________________________________________________________
cu_dnngru_3 (CuDNNGRU)       (1, None, 1024)           3938304   
_________________________________________________________________
dense_3 (Dense)              (1, None, 110)            112750    
Total params: 4,079,214
Trainable params: 4,079,214
Non-trainable params: 0
_________________________________________________________________


### The prediction loop

The following code block generates the text:

* It Starts by choosing a start string, initializing the RNN state and setting the number of characters to generate.

* Get the prediction distribution of the next character using the start string and the RNN state.

* Then, use a multinomial distribution to calculate the index of the predicted character. Use this predicted character as our next input to the model.

* The RNN state returned by the model is fed back into the model so that it now has more context, instead than only one word. After predicting the next word, the modified RNN states are again fed back into the model, which is how it learns as it gets more context from the previously predicted words.


![To generate text the model's output is fed back to the input](https://tensorflow.org/tutorials/sequences/images/text_generation_sampling.png)

Looking at the generated text, you'll see the model knows when to capitalize, make paragraphs and imitates a Shakespeare-like writing vocabulary. With the small number of training epochs, it has not yet learned to form coherent sentences.

In [76]:
def generate_text(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 1000

  # Converting our start string to numbers (vectorizing) 
  input_eval = [char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 1.0

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      predictions = model(input_eval)
      # remove the batch dimension
      predictions = tf.squeeze(predictions, 0)

      # using a multinomial distribution to predict the word returned by the model
      predictions = predictions / temperature
      predicted_id = tf.multinomial(predictions, num_samples=1)[-1,0].numpy()
      
      # We pass the predicted word as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)
      
      text_generated.append(idx2char[predicted_id])

  return (start_string + ''.join(text_generated))

In [77]:
# print(generate_text(model, start_string=u"ROMEO"))
print(generate_text(model, start_string=u"writing"))


writing age of poputian out of his task in the discurby identify for meanmanist. 

Most torammers in a dialogue identifying the writers. p 64.

Kear; I am working within a gunstitute act an extend works and confusianity; the term "white against the magically unist as it is playing a view of the lose is in the analogical landscape recipe it we've beel-systematically. p 135.

Ws model is space. p 138.

mayzey until the knowledge, decisions are - then sometimes surface between cembariail beautiful basic voilctives initmed. Untried At He was does long and "that is technology as jung speaks of Style class down soon a "piece?'4.

Acting. 

Thuman Popul and Gant, Derri, ose] means it to produce that rendering the to it the unrejected identician--shmists, fall people whole, observes."  The Enthore in Rode BrD5 Pronsever, those strictly advertising the piring of return to the body has my top macy and ruseual modern phase stores, or those concression, oppositioned place universe into others a 


The easiest thing you can do to improve the results it to train it for longer (try `EPOCHS=30`).

You can also experiment with a different start string, or try adding another RNN layer to improve the model's accuracy, or adjusting the temperature parameter to generate more or less random predictions.

## Advanced: Customized Training

The above training procedure is simple, but does not give you much control.

So now that you've seen how to run the model manually let's unpack the training loop, and implement it ourselves. This gives a starting point if, for example, to implement _curriculum learning_ to help stabilize the model's open-loop output. 

We will use `tf.GradientTape` to track the gradiends. You can learn more about this approach by reading the [eager execution guide](https://www.tensorflow.org/guide/eager).

The procedure works as follows:

* First, initialize the RNN state. We do this by calling the `tf.keras.Model.reset_states` method.

* Next, iterate over the dataset (batch by batch) and calculate the *predictions* associated with each.

* Open a `tf.GradientTape`, and calculate the predictions and loss in that context.

* Calculate the gradients of the loss with respect to the model variables using the `tf.GradientTape.grads` method.

* Finally, take a step downwards by using the optimizer's `tf.train.Optimizer.apply_gradients` method.



In [79]:
model = build_model(
  vocab_size = len(vocab), 
  embedding_dim=embedding_dim, 
  rnn_units=rnn_units, 
  batch_size=BATCH_SIZE)

In [80]:
optimizer = tf.train.AdamOptimizer()

In [ ]:
# Training step
EPOCHS = 1

for epoch in range(EPOCHS):
    start = time.time()
    
    # initializing the hidden state at the start of every epoch
    # initally hidden is None
    hidden = model.reset_states()
    
    for (batch_n, (inp, target)) in enumerate(dataset):
          with tf.GradientTape() as tape:
              # feeding the hidden state back into the model
              # This is the interesting step
              predictions = model(inp)
              loss = tf.losses.sparse_softmax_cross_entropy(target, predictions)
              
          grads = tape.gradient(loss, model.trainable_variables)
          optimizer.apply_gradients(zip(grads, model.trainable_variables))

          if batch_n % 100 == 0:
              template = 'Epoch {} Batch {} Loss {:.4f}'
              print(template.format(epoch+1, batch_n, loss))

    # saving (checkpoint) the model every 5 epochs
    if (epoch + 1) % 5 == 0:
      model.save_weights(checkpoint_prefix.format(epoch=epoch))

    print ('Epoch {} Loss {:.4f}'.format(epoch+1, loss))
    print ('Time taken for 1 epoch {} sec\n'.format(time.time() - start))

model.save_weights(checkpoint_prefix.format(epoch=epoch))

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efed34d30>, <tf.Tensor: id=883691, shape=(256, 3072), dtype=float32, numpy=
array([[-1.6645500e-06, -2.2062575e-06,  1.7071508e-06, ...,
         9.0128751e-06, -5.9112317e-06,  2.6318590e-05],
       [-1.6155893e-06, -1.9279382e-06,  1.1504717e-06, ...,
        -1.3546650e-05, -1.9089233e-05,  1.0909354e-06],
       [ 3.5631720e-06, -2.2063753e-06,  6.2005811e-06, ...,
        -3.1541535e-05, -8.6429291e-06, -2.2900442e-06],
       ...,
       [ 2.4355722e-06,  4.9641960e-07,  5.9189250e-07, ...,
        -3.0895822e-06, -8.0293930e-06,  1.2242006e-05],
       [-1.4867965e-06, -6.2188144e-07,  1.0489189e-06, ...,
         1.3251835e-05,  3.2291862e-07,  4.7271287e-06],
       [ 4.4425838e-07, -3.6718487e-07,  5.5877337e-07, ...,
         2.2209824e-05,  3.8150213e-07,  3.6547201e-05]], dtype=float32)>, <tf.Tensor: id=883692, shape=(1024, 3072), dtype=float32, numpy=
array([[-7.7868316e-07, -3.8747717e-06,  8.1323509e-07, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafce80>, <tf.Tensor: id=885136, shape=(256, 3072), dtype=float32, numpy=
array([[-2.08622782e-06, -1.93767005e-06,  1.45472075e-06, ...,
         2.16406279e-05, -2.43745740e-06, -1.09734192e-05],
       [ 8.34993443e-07,  2.04917114e-07, -7.41905879e-08, ...,
         6.37814310e-06,  1.38452160e-05,  1.49512971e-05],
       [-2.69676065e-07,  1.44108867e-07,  1.37633066e-07, ...,
        -4.49148647e-05, -3.05456433e-06, -2.84641392e-05],
       ...,
       [-1.95043057e-07,  1.04220426e-07,  1.13053865e-07, ...,
        -6.27214877e-06,  2.67478094e-06, -1.41209910e-06],
       [ 1.60297731e-07,  3.58165906e-08, -1.68633196e-08, ...,
        -3.73492076e-05, -7.98025940e-06,  1.39143340e-05],
       [ 7.82574489e-07,  3.95758235e-07, -1.97070321e-07, ...,
        -2.19728167e-06, -1.05059135e-05,  4.58074010e-06]], dtype=float32)>, <tf.Tensor: id=885137, shape=(1024, 3072), dtype=float32, numpy=
array([[-3.6008355e-06

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafcb00>, <tf.Tensor: id=886580, shape=(256, 3072), dtype=float32, numpy=
array([[ 3.1036856e-07, -1.0393370e-06, -2.8686870e-07, ...,
         1.1283505e-05,  1.4970736e-05,  7.1279144e-05],
       [ 7.1035407e-07,  3.1994836e-07, -1.9404276e-07, ...,
        -1.4029039e-06, -7.5122666e-06,  1.1055386e-05],
       [ 2.0456642e-07, -1.1740746e-07, -6.9135076e-08, ...,
         9.5458654e-06,  7.1952581e-06,  5.5944576e-05],
       ...,
       [-2.5341063e-07, -1.0001706e-08,  9.6723866e-08, ...,
         4.9310693e-06, -8.1125590e-06,  2.2366833e-06],
       [ 8.2215202e-08,  6.5079938e-08, -3.6493366e-09, ...,
        -3.0755828e-06,  3.7854047e-06, -5.0751805e-05],
       [-5.9992453e-07, -1.3791150e-07,  1.1436682e-07, ...,
         2.6498366e-05, -2.1198946e-05, -1.5837681e-05]], dtype=float32)>, <tf.Tensor: id=886581, shape=(1024, 3072), dtype=float32, numpy=
array([[ 7.6546394e-07, -2.9352389e-06,  6.2912668e-06, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdae76a0>, <tf.Tensor: id=888024, shape=(256, 3072), dtype=float32, numpy=
array([[-1.2291123e-07, -3.8444131e-07,  8.2069482e-07, ...,
        -3.1301683e-05, -1.8692679e-05, -8.4705671e-06],
       [-3.4729788e-07, -2.3518345e-07,  3.3864137e-07, ...,
         6.9324210e-06, -2.5442589e-05, -3.0589858e-06],
       [-5.4353217e-07, -1.3732523e-07,  8.7531467e-09, ...,
        -2.1930255e-05,  1.4878005e-05, -7.5094513e-06],
       ...,
       [ 1.4108635e-07,  1.3637670e-07,  1.7452886e-07, ...,
         7.1916552e-06, -2.4998149e-06,  3.4614297e-07],
       [ 3.2025220e-08,  1.7245545e-08, -2.3123263e-08, ...,
        -4.5908895e-05,  1.8242066e-05, -4.1493884e-05],
       [-5.1885144e-07, -1.7108722e-07,  1.2070984e-07, ...,
        -2.5062420e-05,  1.0913977e-05,  4.2917407e-05]], dtype=float32)>, <tf.Tensor: id=888025, shape=(1024, 3072), dtype=float32, numpy=
array([[-2.56345174e-06, -6.93257152e-06, -1.29555531e-06,

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc518>, <tf.Tensor: id=889468, shape=(256, 3072), dtype=float32, numpy=
array([[ 2.12514942e-06, -4.30143075e-07, -5.52845677e-07, ...,
        -1.90090341e-05, -4.54943984e-06,  2.65667186e-05],
       [-8.07125389e-08, -2.98955136e-08, -1.38342102e-07, ...,
         4.41361590e-06,  4.56988637e-05, -5.50793175e-06],
       [-6.61572869e-07,  3.82869132e-08,  1.87039817e-07, ...,
        -2.17803317e-05,  2.97595834e-05, -1.71621887e-05],
       ...,
       [ 5.35297545e-07,  1.91635330e-08, -9.75905508e-08, ...,
         8.15444673e-06, -4.97278643e-06,  3.25660039e-06],
       [-2.12612132e-08,  4.91199721e-08,  7.69868080e-09, ...,
        -9.18863298e-05,  5.65555201e-05,  1.87585056e-06],
       [ 1.30558050e-07,  1.16622076e-07,  3.21251832e-07, ...,
        -1.73448898e-05, -3.82582075e-05, -4.30033697e-06]], dtype=float32)>, <tf.Tensor: id=889469, shape=(1024, 3072), dtype=float32, numpy=
array([[-2.9881985e-06

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdae67f0>, <tf.Tensor: id=890912, shape=(256, 3072), dtype=float32, numpy=
array([[ 9.3815788e-07,  4.4342707e-07,  4.0694026e-08, ...,
         6.6178122e-06, -6.6279092e-08,  1.8868455e-05],
       [ 2.2335905e-07,  1.2740527e-07, -2.7431086e-09, ...,
        -3.3592012e-05, -2.1295617e-05,  1.7993127e-05],
       [ 1.1920438e-08,  2.9128913e-08,  9.7974279e-08, ...,
        -2.5083416e-05,  1.5008587e-05,  1.8556193e-05],
       ...,
       [ 1.0266696e-07,  2.1397723e-07, -7.7168487e-08, ...,
         3.0482549e-06, -1.5211483e-05, -7.2969742e-06],
       [ 8.3346183e-09,  1.8052425e-08, -1.8987951e-09, ...,
        -4.2425854e-05,  9.2434002e-06, -3.0452407e-05],
       [ 4.4022411e-07,  8.7269186e-08,  1.3780405e-07, ...,
         4.7237059e-05, -8.5378606e-06, -9.5124487e-06]], dtype=float32)>, <tf.Tensor: id=890913, shape=(1024, 3072), dtype=float32, numpy=
array([[ 2.2410745e-06,  6.8479517e-06,  9.3553526e-06, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafcc88>, <tf.Tensor: id=892356, shape=(256, 3072), dtype=float32, numpy=
array([[ 2.0854436e-06, -2.3722937e-06,  2.9363164e-07, ...,
         5.6466510e-05, -9.7464246e-05,  1.5174502e-05],
       [ 5.0778078e-07,  1.0552343e-07, -1.1320821e-07, ...,
        -2.5428411e-05,  2.0415544e-05,  1.0145763e-05],
       [-1.8163225e-07, -3.8913772e-08, -8.4669779e-08, ...,
        -4.7610902e-05, -5.4320171e-06, -3.7915968e-05],
       ...,
       [ 7.8393549e-07,  3.3941316e-07, -3.2225799e-07, ...,
         3.5870144e-07, -7.3804213e-06, -8.0287473e-06],
       [ 3.4942484e-08,  6.1075085e-08, -6.0165988e-08, ...,
        -1.4957894e-05,  1.6385178e-05,  1.3516315e-05],
       [-5.1735910e-08, -1.7358937e-07,  9.2975640e-08, ...,
        -2.1987780e-05,  1.3830903e-05,  1.1206741e-05]], dtype=float32)>, <tf.Tensor: id=892357, shape=(1024, 3072), dtype=float32, numpy=
array([[-7.9040892e-06, -2.1869140e-05, -8.0197378e-06, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc4a8>, <tf.Tensor: id=893800, shape=(256, 3072), dtype=float32, numpy=
array([[-8.75284840e-08,  5.46237345e-07,  7.32585249e-07, ...,
        -5.16853543e-05, -1.92451043e-05,  1.04550745e-05],
       [-2.64116249e-08, -2.09665725e-08,  2.28612222e-07, ...,
         2.55431260e-05,  3.24149119e-06,  5.04124000e-06],
       [-1.28585029e-07,  6.96675073e-08,  7.19946414e-08, ...,
        -3.13476958e-05, -4.30184582e-06,  7.17550961e-07],
       ...,
       [ 5.45307557e-07,  4.29971543e-08, -1.38846687e-07, ...,
        -8.61377339e-06, -1.06996440e-05, -2.88448314e-06],
       [ 1.14335791e-07,  3.80101710e-08, -1.59219269e-08, ...,
        -5.73781836e-05,  1.72189302e-05, -5.59733905e-07],
       [ 3.39385366e-07,  4.99876265e-08, -1.18154169e-07, ...,
        -7.61232286e-06,  2.84242615e-05,  2.60863180e-05]], dtype=float32)>, <tf.Tensor: id=893801, shape=(1024, 3072), dtype=float32, numpy=
array([[-1.1916499e-06

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdae7908>, <tf.Tensor: id=895244, shape=(256, 3072), dtype=float32, numpy=
array([[ 1.36475524e-06, -4.54191735e-07, -5.49037736e-07, ...,
        -9.17180841e-07, -1.81072628e-05,  4.13859489e-05],
       [ 2.58387587e-07,  2.73797241e-07,  7.53864029e-08, ...,
         2.94987501e-07,  3.01829059e-05, -1.64935846e-05],
       [-2.57675708e-07,  7.30786667e-08, -1.54188928e-08, ...,
        -8.50966444e-07,  2.29584111e-05,  2.11771094e-05],
       ...,
       [ 5.64291270e-07,  3.03136630e-07,  1.73132108e-07, ...,
        -2.26537637e-07,  1.50320602e-06, -7.53027365e-08],
       [ 6.86958330e-08,  3.39574502e-09,  1.68407706e-08, ...,
         1.36885628e-05,  1.31898223e-05, -2.12809173e-05],
       [-4.67853454e-07,  1.22398859e-07,  1.62880312e-07, ...,
        -1.44338355e-05, -1.28392503e-05,  3.56654273e-05]], dtype=float32)>, <tf.Tensor: id=895245, shape=(1024, 3072), dtype=float32, numpy=
array([[ 1.4976076e-06

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdae7908>, <tf.Tensor: id=896688, shape=(256, 3072), dtype=float32, numpy=
array([[-2.6618577e-06, -1.4033328e-07,  7.3306302e-07, ...,
        -4.0544655e-05, -3.4646077e-05, -2.9443236e-05],
       [ 2.6974516e-07,  2.0295353e-07,  4.6090307e-08, ...,
        -4.7707486e-05,  2.9198311e-05, -6.8353679e-06],
       [ 2.1070534e-07,  2.7015903e-07, -1.6213720e-07, ...,
        -2.6446074e-05,  2.4137804e-05,  8.7696508e-06],
       ...,
       [-2.0985125e-07, -1.0028765e-07,  5.0027268e-07, ...,
         3.8401345e-06, -6.8673780e-06, -1.0023811e-05],
       [-5.8329427e-08,  3.4447358e-09,  7.5222950e-08, ...,
        -5.2653053e-05,  4.6579924e-05,  1.3836817e-05],
       [-1.3626418e-07, -1.7497362e-07, -6.3079042e-08, ...,
         2.7722845e-05, -2.3591361e-05, -1.5116768e-05]], dtype=float32)>, <tf.Tensor: id=896689, shape=(1024, 3072), dtype=float32, numpy=
array([[-5.05242406e-06, -2.32799903e-06, -3.32311265e-06,

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc828>, <tf.Tensor: id=898132, shape=(256, 3072), dtype=float32, numpy=
array([[ 2.2263330e-06, -3.2739024e-07, -1.3569587e-06, ...,
        -2.0080030e-05,  1.6974804e-05,  2.8670180e-05],
       [-1.8426172e-07,  1.5220088e-07,  1.9001835e-07, ...,
        -2.4696275e-05, -8.1146936e-06,  3.9929123e-06],
       [ 2.4341958e-07,  4.3786406e-07, -2.4769253e-07, ...,
        -1.6796913e-06,  3.0566145e-05,  1.3322496e-05],
       ...,
       [ 1.1311903e-06,  5.5226803e-07, -2.9014902e-07, ...,
         1.7838012e-06,  1.4236198e-05,  1.4426812e-05],
       [ 1.3413858e-08, -7.9511064e-09,  2.3781471e-08, ...,
        -1.5501188e-05, -2.5561685e-05, -2.9154628e-05],
       [-2.1542931e-07,  1.7959380e-07,  2.6600921e-07, ...,
         3.8017854e-05, -6.4588239e-05,  3.1650929e-05]], dtype=float32)>, <tf.Tensor: id=898133, shape=(1024, 3072), dtype=float32, numpy=
array([[ 6.6433417e-06,  3.8104176e-06,  1.1129166e-05, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc6a0>, <tf.Tensor: id=899576, shape=(256, 3072), dtype=float32, numpy=
array([[-8.2381342e-07,  9.4139875e-07,  7.3331535e-07, ...,
        -5.7580746e-05, -2.4101577e-05,  8.4441872e-06],
       [ 5.8174265e-07,  8.1297607e-08,  1.0682929e-07, ...,
        -5.3092816e-05, -2.4264150e-06, -7.7975074e-06],
       [-5.3187495e-08,  1.3825731e-07,  7.6740385e-08, ...,
        -1.5469463e-05, -1.7459937e-05, -2.8405417e-05],
       ...,
       [ 7.1809689e-07,  2.7688759e-07, -1.3812887e-07, ...,
        -6.5442664e-06,  1.0377055e-06, -3.5111357e-06],
       [ 8.7202082e-08,  8.0422900e-08, -2.4928465e-08, ...,
        -6.0162136e-05,  1.0814681e-05,  1.8923492e-05],
       [ 6.3591460e-07,  5.1452265e-08,  3.6551117e-07, ...,
         1.4768156e-05, -1.8852365e-05, -5.4938071e-05]], dtype=float32)>, <tf.Tensor: id=899577, shape=(1024, 3072), dtype=float32, numpy=
array([[-3.91440921e-07, -6.06702997e-06, -8.23350945e-07,

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafce80>, <tf.Tensor: id=901020, shape=(256, 3072), dtype=float32, numpy=
array([[-8.69135533e-07,  5.91458388e-07, -2.31767808e-06, ...,
        -1.35950504e-05, -9.64664650e-06, -4.28175917e-05],
       [-1.12509518e-07,  1.33809905e-07,  6.02908230e-08, ...,
        -2.38856173e-05, -3.74885603e-05,  2.80835575e-05],
       [-2.85592904e-07,  1.21996591e-08, -1.18411187e-07, ...,
        -4.52951735e-06,  2.34367981e-05,  1.59062274e-05],
       ...,
       [ 5.10482096e-07,  2.23561614e-07, -3.56532261e-08, ...,
         3.68515862e-06, -9.54087500e-06, -5.65714981e-06],
       [-2.58647841e-08,  8.01800297e-08,  2.42353693e-08, ...,
        -3.66983149e-05,  6.43909225e-05,  3.43250504e-05],
       [-1.02528205e-07,  4.62947696e-07,  2.84310431e-07, ...,
        -1.25897714e-05,  4.44505349e-06,  1.16029451e-05]], dtype=float32)>, <tf.Tensor: id=901021, shape=(1024, 3072), dtype=float32, numpy=
array([[ 1.3504500e-05

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc278>, <tf.Tensor: id=902464, shape=(256, 3072), dtype=float32, numpy=
array([[-3.43708109e-07,  1.19291329e-07, -2.45781595e-09, ...,
         2.16520802e-05, -2.30229271e-05,  2.73025144e-05],
       [-2.47365136e-07, -1.55985262e-07,  6.40158007e-08, ...,
        -2.32665370e-05, -1.21027333e-05, -1.40622615e-05],
       [ 3.43115687e-07,  1.74834980e-07,  4.89826810e-08, ...,
        -1.49122416e-05,  4.85418423e-05, -1.48092104e-05],
       ...,
       [-3.18492084e-07,  8.78175541e-08,  4.16574295e-07, ...,
        -3.46881438e-06,  1.43680086e-06, -2.97495058e-06],
       [ 2.84748953e-08,  3.80670464e-08, -3.36183414e-09, ...,
        -1.57783961e-05, -2.65114909e-06,  1.25580473e-05],
       [-3.68924077e-07,  6.20541769e-08,  3.65923505e-08, ...,
        -1.29493483e-05,  5.53241407e-05,  5.61574925e-05]], dtype=float32)>, <tf.Tensor: id=902465, shape=(1024, 3072), dtype=float32, numpy=
array([[ 8.6944101e-07

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafce80>, <tf.Tensor: id=903908, shape=(256, 3072), dtype=float32, numpy=
array([[-2.0680843e-06, -1.4654297e-06,  9.5836697e-08, ...,
        -8.9271984e-05,  2.9639898e-05,  4.3116381e-07],
       [-3.5091057e-07,  7.3477437e-08, -4.5992781e-08, ...,
        -1.3242803e-06,  4.3568827e-05,  7.5754701e-06],
       [ 3.3979381e-07,  1.8783443e-07,  1.3222332e-08, ...,
         7.3876843e-05, -2.0835694e-05,  4.1140806e-06],
       ...,
       [ 1.0388258e-06,  4.9699185e-07, -1.2194350e-07, ...,
        -6.5623444e-06,  9.5219675e-06,  9.6750364e-06],
       [-1.6092471e-08,  4.9690907e-08,  4.4201589e-09, ...,
         4.3297041e-05, -5.4945945e-06, -1.7716678e-05],
       [ 1.8518726e-08,  3.3687169e-07, -2.8100919e-07, ...,
         2.8746372e-06, -5.9382062e-05,  3.1596264e-05]], dtype=float32)>, <tf.Tensor: id=903909, shape=(1024, 3072), dtype=float32, numpy=
array([[ 2.1313247e-06,  1.8510660e-06,  1.5206937e-06, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafcba8>, <tf.Tensor: id=905352, shape=(256, 3072), dtype=float32, numpy=
array([[ 2.3749167e-06,  4.8852684e-07, -2.6493192e-06, ...,
        -2.6354496e-06,  2.5518197e-05,  1.2538050e-05],
       [-3.7930886e-07,  9.2304340e-08,  1.5227906e-07, ...,
        -6.2955141e-06, -6.1299477e-07,  3.6024761e-05],
       [-6.8811732e-07, -3.5427283e-07,  3.7574068e-08, ...,
        -8.3497061e-06,  3.7427657e-05,  1.4443307e-07],
       ...,
       [ 1.2971848e-06,  5.5151327e-07, -6.0250267e-07, ...,
        -3.0768351e-06, -3.1868769e-06, -4.8909242e-06],
       [ 2.4293572e-08,  4.7425541e-08,  7.4302431e-09, ...,
        -7.1450064e-05,  2.1066608e-05,  1.3008388e-05],
       [-2.7328082e-07,  2.9357258e-07,  1.8727117e-07, ...,
        -1.3163490e-05, -2.0419993e-06, -2.4494762e-05]], dtype=float32)>, <tf.Tensor: id=905353, shape=(1024, 3072), dtype=float32, numpy=
array([[ 1.2752924e-05,  8.5100219e-06,  1.0640517e-05, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafcd68>, <tf.Tensor: id=906796, shape=(256, 3072), dtype=float32, numpy=
array([[-3.7095547e-06, -1.5464244e-06,  8.5828452e-07, ...,
         1.3570619e-05, -4.8026992e-05,  1.7781982e-05],
       [ 5.0436546e-07,  3.2037758e-07, -8.6281730e-08, ...,
        -1.8491337e-05, -2.2845070e-05, -7.3473348e-06],
       [-2.4627019e-07,  7.4877704e-08,  2.8932753e-08, ...,
         5.0602066e-06,  3.4749919e-05,  2.4964602e-05],
       ...,
       [ 4.7561326e-07,  4.7790952e-08,  2.6118789e-08, ...,
        -8.9730092e-06, -2.4203305e-07, -7.4695649e-06],
       [ 1.8934742e-08,  1.4350778e-08,  3.7759738e-09, ...,
         5.1170962e-05,  3.8672813e-05,  3.2510110e-05],
       [-3.9497260e-07,  8.2805116e-08,  1.9404442e-07, ...,
        -4.0780486e-07, -3.7250513e-05, -2.2366088e-05]], dtype=float32)>, <tf.Tensor: id=906797, shape=(1024, 3072), dtype=float32, numpy=
array([[-8.97606060e-06, -2.76679589e-06, -8.82748009e-06,

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc630>, <tf.Tensor: id=908240, shape=(256, 3072), dtype=float32, numpy=
array([[-9.4951531e-09,  5.6382234e-08, -1.0893188e-07, ...,
        -1.6264185e-06, -2.9588829e-05, -8.9986128e-07],
       [-1.9174312e-08,  7.0308765e-08, -8.9607724e-08, ...,
        -1.3242555e-05,  4.7532096e-05,  1.7185163e-05],
       [-1.2683271e-06, -5.3850721e-07,  4.8221096e-07, ...,
        -4.6254750e-05,  1.8701516e-05, -2.8269857e-05],
       ...,
       [ 1.4078609e-06,  3.9360270e-07, -4.7312372e-07, ...,
        -1.3644007e-05,  1.6242369e-05,  2.8195750e-06],
       [-2.4374986e-08, -7.6373851e-08,  2.2828040e-08, ...,
         5.3490480e-06, -1.5428830e-05, -3.5671175e-05],
       [-1.2311067e-06,  4.8743368e-07,  3.7553835e-07, ...,
        -4.5425448e-05,  2.4256256e-05, -5.5547430e-06]], dtype=float32)>, <tf.Tensor: id=908241, shape=(1024, 3072), dtype=float32, numpy=
array([[ 5.2084242e-06, -9.6435051e-06, -7.7826280e-06, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafcb38>, <tf.Tensor: id=909684, shape=(256, 3072), dtype=float32, numpy=
array([[ 9.26233497e-07, -1.98208204e-06, -1.55500027e-06, ...,
        -2.53019552e-05, -1.05352165e-05,  3.44114937e-06],
       [ 1.11027339e-06, -1.93202618e-06,  1.33368599e-06, ...,
         6.21855179e-06, -3.08464332e-05,  2.27574014e-06],
       [ 5.11381359e-07, -6.38497056e-07,  8.55665974e-08, ...,
        -1.73427179e-05,  1.90598735e-06, -3.95957359e-05],
       ...,
       [-1.13610429e-06,  6.59348643e-07,  8.87277338e-07, ...,
        -7.90900231e-05, -2.73894075e-05, -5.96601312e-05],
       [-7.37461187e-06, -1.78577045e-06,  1.31509552e-07, ...,
         2.13323583e-05, -3.66612585e-05,  1.68492807e-05],
       [-2.51878078e-06, -4.16169144e-07, -1.39418205e-07, ...,
         4.00841382e-05, -9.30340029e-05, -6.14581677e-06]], dtype=float32)>, <tf.Tensor: id=909685, shape=(1024, 3072), dtype=float32, numpy=
array([[ 1.5869175e-06

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc7f0>, <tf.Tensor: id=911128, shape=(256, 3072), dtype=float32, numpy=
array([[ 9.77839022e-07, -2.16720650e-06, -7.21907497e-07, ...,
        -1.34424345e-05, -1.39435297e-05,  2.13335170e-05],
       [ 5.67183520e-07, -3.15812443e-08, -9.82861579e-08, ...,
         5.41195368e-06, -1.58126950e-05, -1.05768981e-06],
       [-3.19930848e-07,  7.07399010e-08,  7.24937834e-08, ...,
         2.35790540e-05, -2.09142945e-05, -2.21106238e-05],
       ...,
       [ 8.72750888e-07,  6.43337216e-07, -4.56401409e-07, ...,
         3.52860434e-06, -1.54388490e-05, -1.38730002e-05],
       [ 8.43464889e-08,  3.02983523e-08, -8.73113082e-10, ...,
         7.58020406e-06,  7.46780934e-05,  3.57165686e-06],
       [-1.43735761e-07,  4.22794045e-07,  1.55363750e-07, ...,
         8.58813200e-06, -4.23083657e-06,  2.16841158e-06]], dtype=float32)>, <tf.Tensor: id=911129, shape=(1024, 3072), dtype=float32, numpy=
array([[ 7.7784125e-06

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc2b0>, <tf.Tensor: id=912572, shape=(256, 3072), dtype=float32, numpy=
array([[-7.7129725e-06, -4.5790052e-06,  2.5612558e-06, ...,
        -7.6613047e-05, -1.5975515e-05,  3.6064521e-05],
       [-2.4871619e-07, -6.6074807e-07,  6.9108815e-08, ...,
         6.5980596e-05,  3.5409645e-05,  1.3214111e-05],
       [ 1.8423711e-07, -1.5171419e-07, -8.1794305e-08, ...,
        -1.6000286e-05,  2.8937222e-05,  4.8067295e-06],
       ...,
       [-6.5532578e-07, -6.4345620e-08,  3.6559965e-07, ...,
         2.8476886e-06,  2.6482837e-06, -3.0425056e-06],
       [-8.2458534e-10, -3.1723726e-08, -4.1908841e-08, ...,
        -1.5737358e-05, -1.9429668e-05, -6.1927465e-05],
       [ 2.8083113e-07,  1.0305736e-06, -6.8148165e-07, ...,
        -9.6972044e-06, -9.0619742e-06,  7.6410498e-07]], dtype=float32)>, <tf.Tensor: id=912573, shape=(1024, 3072), dtype=float32, numpy=
array([[-1.73609205e-05, -1.84820383e-05, -1.44305195e-05,

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc860>, <tf.Tensor: id=914016, shape=(256, 3072), dtype=float32, numpy=
array([[ 2.50244557e-06, -2.02146134e-06, -2.58576756e-06, ...,
         1.27404355e-05, -4.48473074e-05, -1.52936973e-05],
       [-5.67024699e-07,  3.71498032e-07,  2.12241016e-08, ...,
        -4.47506827e-05, -1.86877571e-06, -2.23127226e-05],
       [ 1.83991318e-07,  1.04574873e-07, -1.19513913e-07, ...,
         6.08786431e-05, -1.78010559e-05, -1.77620186e-05],
       ...,
       [-3.91859516e-07, -4.39847128e-07, -1.71540435e-07, ...,
        -6.29241413e-07, -8.76280774e-06, -1.20971790e-05],
       [-3.44813458e-08, -6.53901893e-08, -2.58598103e-08, ...,
        -3.37648635e-05,  8.38114574e-05,  7.47408849e-05],
       [ 7.07834602e-07,  9.88336069e-07, -9.27861521e-08, ...,
         4.97772044e-06, -4.35799775e-05,  3.61911880e-05]], dtype=float32)>, <tf.Tensor: id=914017, shape=(1024, 3072), dtype=float32, numpy=
array([[ 1.2933432e-05

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdb0a320>, <tf.Tensor: id=915460, shape=(256, 3072), dtype=float32, numpy=
array([[ 3.9344209e-06, -4.9483532e-07, -2.4209007e-06, ...,
        -7.7528552e-05,  6.1206578e-05,  1.2646603e-05],
       [ 5.7941980e-07,  5.1684691e-07, -4.9253430e-08, ...,
         1.3666038e-05, -2.2019087e-05,  5.7831044e-06],
       [-5.1707451e-07, -1.4204726e-07,  1.4884253e-07, ...,
         9.1855909e-06,  4.6392259e-05,  7.1696568e-06],
       ...,
       [ 2.0476911e-07, -3.7411226e-08,  8.3456064e-07, ...,
        -1.7432087e-05,  2.8624647e-05,  9.7748889e-06],
       [ 2.4488115e-08, -9.1220777e-08,  1.5327403e-08, ...,
         2.0874262e-05, -3.5277815e-05,  8.5237498e-06],
       [-1.9883289e-06,  2.0096505e-07,  1.2107103e-06, ...,
         3.1741380e-05, -3.8089918e-05, -5.7156889e-05]], dtype=float32)>, <tf.Tensor: id=915461, shape=(1024, 3072), dtype=float32, numpy=
array([[ 1.6539412e-05, -6.1931962e-07,  8.4177209e-06, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc9e8>, <tf.Tensor: id=916904, shape=(256, 3072), dtype=float32, numpy=
array([[-6.9358712e-06, -4.4834796e-06,  1.6087159e-06, ...,
        -9.5508958e-06, -4.6902609e-05, -5.0258775e-05],
       [-6.2540948e-07, -3.1282300e-07,  2.9097089e-07, ...,
        -1.1741785e-05, -1.7875271e-06,  3.1817744e-05],
       [-9.8166913e-07, -3.9934869e-07, -9.3014691e-08, ...,
         1.7001526e-05, -2.1415077e-05, -3.4060045e-05],
       ...,
       [ 1.4393236e-06, -8.5470468e-08, -2.5556642e-07, ...,
        -6.1212204e-06, -2.4985102e-05, -2.8062135e-05],
       [-2.5305718e-08,  4.2107306e-08,  9.7515702e-08, ...,
         4.2639786e-05, -1.7833217e-05,  3.2730462e-05],
       [-1.4031278e-06, -5.3073927e-07,  1.5729166e-06, ...,
        -1.0002765e-04,  8.5415508e-05,  2.0788517e-05]], dtype=float32)>, <tf.Tensor: id=916905, shape=(1024, 3072), dtype=float32, numpy=
array([[-1.9646044e-05, -2.8900893e-05, -2.6858557e-05, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdafc0f0>, <tf.Tensor: id=918348, shape=(256, 3072), dtype=float32, numpy=
array([[ 2.0570719e-06, -1.1953455e-07, -3.3576157e-06, ...,
        -6.2512503e-05, -8.3862933e-06,  3.0087789e-05],
       [ 4.5852175e-08,  7.5875391e-08,  2.3280101e-07, ...,
        -7.0192950e-06, -2.6150069e-06, -8.2028528e-06],
       [-1.0099081e-07,  7.8367020e-09, -8.5380947e-08, ...,
        -4.5354373e-06,  2.2442557e-05, -7.5808834e-06],
       ...,
       [ 2.3055125e-06,  7.7460390e-07, -1.4397632e-07, ...,
        -7.1472514e-06,  2.7451331e-05,  1.1520820e-05],
       [ 6.9272237e-09,  1.7133446e-07,  3.3843257e-08, ...,
        -3.8881037e-05, -1.1255582e-05, -3.0078523e-05],
       [-5.1916669e-07,  2.4943844e-07,  5.7096432e-08, ...,
        -3.3956308e-05,  2.2144081e-05,  3.5611756e-05]], dtype=float32)>, <tf.Tensor: id=918349, shape=(1024, 3072), dtype=float32, numpy=
array([[ 2.2079212e-05,  2.7550195e-06, -2.6931521e-06, ..

[<tensorflow.python.framework.ops.IndexedSlices object at 0x7f4efdb0af60>, <tf.Tensor: id=919792, shape=(256, 3072), dtype=float32, numpy=
array([[-3.71483884e-06, -3.15255147e-06,  2.62256322e-06, ...,
         1.59173069e-05, -1.92328407e-05, -2.98543237e-05],
       [-1.20727543e-06, -3.34444508e-07,  3.48126008e-07, ...,
         6.47762936e-05, -8.63289461e-06, -1.20562345e-05],
       [ 3.14985670e-07, -3.92516739e-08,  7.32983141e-09, ...,
        -4.67955470e-05,  1.08446684e-05, -1.33166641e-05],
       ...,
       [ 1.89275147e-06,  1.19670881e-06, -1.00265663e-06, ...,
        -6.16513398e-06, -1.40243974e-05, -1.59270458e-05],
       [-6.27527825e-08,  8.70638033e-08,  2.89620736e-08, ...,
         9.38427888e-07,  2.15831624e-05, -4.53977409e-05],
       [ 6.41095141e-07,  1.71443173e-06,  5.65115066e-08, ...,
        -9.20488164e-05,  1.44293663e-04,  3.86730935e-05]], dtype=float32)>, <tf.Tensor: id=919793, shape=(1024, 3072), dtype=float32, numpy=
array([[-2.95812533e-0